import transactions as t
import gspread

sa = gspread.service_account()
sh = sa.open("Pynubank")
wks= sh.worksheet("Página1")

card_statements_filename = "../data/card_statements_18-06-2022/raw.json"
account_feed_filename = "../data/account_feed_18-06-2022/raw.json"

# Data generated by mockHttpClient()
#card_statements_filename = "../data/2022-06-18/card_statements/raw.json"
#account_feed_filename = "../data/2022-06-18/account_feed/raw.json"

myTransactions = t.getMyTransactions(card_statements_filename, account_feed_filename);

#transactionList = []
#for i in myTransactions["credit"]:
#    l = [i.description, i.amount, str(i.date)]
#    transactionList += [l]

#print(transactionList)

nRows = len(myTransactions["credit"])
spreadRange = "A1:C" + str(nRows)
print(spreadRange)

#wks.update(spreadRange, transactionList)
#wks.update('A1:B2', [[1, 2], [3, 4]])


'''
row = 1
col = 1

for i in myTransactions["credit"]:

    if col == 1:
        value = i.description
    if col == 2:
        value = i.amount
    if col == 3:
        value = str(i.date)

    wks.update_cell(row, col, value)

    col += 1
    if col == 4:
        col = 1
        row += 1
''' 


    #print("{0: <32}{1: <10}{2: <24}".format(i.description, i.amount, str(i.date)))
    
print("-----\n")

for i in myTransactions["debit"]:
    print("-----")
    print("Typename: " + i.typename)
    print("Title: " + i.title)
    print("Detail: " + i.detail)
    print("Date: " + str(i.date))
    #print("{0: <32}{1: <32}{2: <40}{3: <8}".format(i.typename, i.title, i.detail ,str(i.date)))

#print(len(myTransactions["debit"]))
#print(len(myTransactions["credit"]))
